export interface SuburbEntry {
  suburb: string;
  state: string;
  postcode: string;
}

// [suburb, state, postcode]
const SUBURBS_RAW: [string, string, string][] = [
  // VIC — Melbourne CBD & surrounds
  ["Melbourne",          "VIC", "3000"],
  ["Southbank",          "VIC", "3006"],
  ["Docklands",          "VIC", "3008"],
  ["West Melbourne",     "VIC", "3003"],
  ["North Melbourne",    "VIC", "3051"],
  ["Parkville",          "VIC", "3052"],
  // VIC — Inner North
  ["Carlton",            "VIC", "3053"],
  ["Carlton North",      "VIC", "3054"],
  ["Fitzroy",            "VIC", "3065"],
  ["Fitzroy North",      "VIC", "3068"],
  ["Collingwood",        "VIC", "3066"],
  ["Abbotsford",         "VIC", "3067"],
  ["Richmond",           "VIC", "3121"],
  ["Brunswick",          "VIC", "3056"],
  ["Brunswick East",     "VIC", "3057"],
  ["Brunswick West",     "VIC", "3055"],
  ["Coburg",             "VIC", "3058"],
  ["Coburg North",       "VIC", "3058"],
  ["Pascoe Vale",        "VIC", "3044"],
  ["Pascoe Vale South",  "VIC", "3044"],
  ["Oak Park",           "VIC", "3046"],
  ["Glenroy",            "VIC", "3046"],
  ["Broadmeadows",       "VIC", "3047"],
  ["Dallas",             "VIC", "3047"],
  ["Tullamarine",        "VIC", "3043"],
  ["Preston",            "VIC", "3072"],
  ["Reservoir",          "VIC", "3073"],
  ["Thomastown",         "VIC", "3074"],
  ["Lalor",              "VIC", "3075"],
  ["Epping",             "VIC", "3076"],
  ["Bundoora",           "VIC", "3083"],
  ["Mill Park",          "VIC", "3082"],
  ["South Morang",       "VIC", "3752"],
  ["Greensborough",      "VIC", "3088"],
  ["Diamond Creek",      "VIC", "3089"],
  ["Eltham",             "VIC", "3095"],
  ["Montmorency",        "VIC", "3094"],
  // VIC — Inner West
  ["Footscray",          "VIC", "3011"],
  ["Yarraville",         "VIC", "3013"],
  ["Seddon",             "VIC", "3011"],
  ["Maribyrnong",        "VIC", "3032"],
  ["Ascot Vale",         "VIC", "3032"],
  ["Flemington",         "VIC", "3031"],
  ["Kensington",         "VIC", "3031"],
  ["Essendon",           "VIC", "3040"],
  ["Moonee Ponds",       "VIC", "3039"],
  ["Newport",            "VIC", "3015"],
  ["Williamstown",       "VIC", "3016"],
  ["Spotswood",          "VIC", "3015"],
  ["Altona",             "VIC", "3018"],
  ["Altona North",       "VIC", "3025"],
  ["Altona Meadows",     "VIC", "3028"],
  ["Laverton",           "VIC", "3028"],
  ["Sunshine",           "VIC", "3020"],
  ["Sunshine North",     "VIC", "3020"],
  ["St Albans",          "VIC", "3021"],
  ["Deer Park",          "VIC", "3023"],
  ["Werribee",           "VIC", "3030"],
  ["Hoppers Crossing",   "VIC", "3029"],
  ["Tarneit",            "VIC", "3029"],
  ["Point Cook",         "VIC", "3030"],
  ["Wyndham Vale",       "VIC", "3024"],
  // VIC — Inner South
  ["South Yarra",        "VIC", "3141"],
  ["Toorak",             "VIC", "3142"],
  ["Prahran",            "VIC", "3181"],
  ["Windsor",            "VIC", "3181"],
  ["Armadale",           "VIC", "3143"],
  ["Glen Iris",          "VIC", "3146"],
  ["Malvern",            "VIC", "3144"],
  ["Malvern East",       "VIC", "3145"],
  ["Caulfield",          "VIC", "3162"],
  ["Caulfield North",    "VIC", "3161"],
  ["Caulfield South",    "VIC", "3162"],
  ["Elsternwick",        "VIC", "3185"],
  ["Ormond",             "VIC", "3204"],
  ["McKinnon",           "VIC", "3204"],
  ["Bentleigh",          "VIC", "3204"],
  ["Bentleigh East",     "VIC", "3165"],
  ["Carnegie",           "VIC", "3163"],
  ["Murrumbeena",        "VIC", "3163"],
  ["Oakleigh",           "VIC", "3166"],
  ["Oakleigh East",      "VIC", "3166"],
  ["Oakleigh South",     "VIC", "3167"],
  ["Huntingdale",        "VIC", "3166"],
  ["Moorabbin",          "VIC", "3189"],
  ["Highett",            "VIC", "3190"],
  ["Cheltenham",         "VIC", "3192"],
  ["Beaumaris",          "VIC", "3193"],
  ["Mentone",            "VIC", "3194"],
  ["Mordialloc",         "VIC", "3195"],
  ["Parkdale",           "VIC", "3195"],
  ["Sandringham",        "VIC", "3191"],
  ["Hampton",            "VIC", "3188"],
  ["Brighton",           "VIC", "3186"],
  ["Brighton East",      "VIC", "3187"],
  // VIC — Port Phillip & St Kilda
  ["St Kilda",           "VIC", "3182"],
  ["Elwood",             "VIC", "3184"],
  ["Port Melbourne",     "VIC", "3207"],
  ["Albert Park",        "VIC", "3206"],
  ["South Melbourne",    "VIC", "3205"],
  // VIC — Inner East
  ["Hawthorn",           "VIC", "3122"],
  ["Hawthorn East",      "VIC", "3123"],
  ["Camberwell",         "VIC", "3124"],
  ["Canterbury",         "VIC", "3126"],
  ["Balwyn",             "VIC", "3103"],
  ["Balwyn North",       "VIC", "3104"],
  ["Kew",                "VIC", "3101"],
  ["Kew East",           "VIC", "3102"],
  ["Box Hill",           "VIC", "3128"],
  ["Box Hill North",     "VIC", "3129"],
  ["Box Hill South",     "VIC", "3128"],
  ["Blackburn",          "VIC", "3130"],
  ["Doncaster",          "VIC", "3108"],
  ["Doncaster East",     "VIC", "3109"],
  ["Templestowe",        "VIC", "3106"],
  ["Templestowe Lower",  "VIC", "3107"],
  ["Burwood",            "VIC", "3125"],
  ["Burwood East",       "VIC", "3151"],
  ["Ashwood",            "VIC", "3147"],
  ["Chadstone",          "VIC", "3148"],
  ["Glen Waverley",      "VIC", "3150"],
  ["Mount Waverley",     "VIC", "3149"],
  ["Wheelers Hill",      "VIC", "3150"],
  ["Mulgrave",           "VIC", "3170"],
  // VIC — South East
  ["Clayton",            "VIC", "3168"],
  ["Clayton South",      "VIC", "3169"],
  ["Springvale",         "VIC", "3171"],
  ["Springvale South",   "VIC", "3172"],
  ["Noble Park",         "VIC", "3174"],
  ["Dandenong",          "VIC", "3175"],
  ["Dandenong North",    "VIC", "3175"],
  ["Rowville",           "VIC", "3178"],
  ["Ferntree Gully",     "VIC", "3156"],
  ["Bayswater",          "VIC", "3153"],
  ["Boronia",            "VIC", "3155"],
  ["Wantirna",           "VIC", "3152"],
  ["Frankston",          "VIC", "3199"],
  ["Frankston North",    "VIC", "3200"],
  ["Langwarrin",         "VIC", "3910"],
  ["Mount Eliza",        "VIC", "3930"],
  ["Mornington",         "VIC", "3931"],
  ["Mount Martha",       "VIC", "3934"],
  ["Rosebud",            "VIC", "3939"],
  ["Rye",                "VIC", "3941"],
  ["Sorrento",           "VIC", "3943"],
  // VIC — Regional
  ["Geelong",            "VIC", "3220"],
  ["Geelong West",       "VIC", "3218"],
  ["Newtown",            "VIC", "3220"],
  ["Highton",            "VIC", "3216"],
  ["Belmont",            "VIC", "3216"],
  ["Grovedale",          "VIC", "3216"],
  ["South Geelong",      "VIC", "3220"],
  ["Ballarat",           "VIC", "3350"],
  ["Ballarat East",      "VIC", "3350"],
  ["Bendigo",            "VIC", "3550"],
  ["Kangaroo Flat",      "VIC", "3555"],
  ["Strathfieldsaye",    "VIC", "3551"],
  ["Shepparton",         "VIC", "3630"],
  ["Mooroopna",          "VIC", "3629"],
  ["Mildura",            "VIC", "3500"],
  ["Irymple",            "VIC", "3498"],
  ["Warrnambool",        "VIC", "3280"],
  ["Traralgon",          "VIC", "3844"],
  ["Morwell",            "VIC", "3840"],
  ["Moe",                "VIC", "3825"],
  ["Echuca",             "VIC", "3564"],
  ["Wodonga",            "VIC", "3690"],
  ["Swan Hill",          "VIC", "3585"],
  ["Horsham",            "VIC", "3400"],
  ["Wangaratta",         "VIC", "3677"],
  ["Sale",               "VIC", "3850"],
  // VIC — Outer South-East (Casey-Cardinia)
  ["Pakenham",           "VIC", "3810"],
  ["Beaconsfield",       "VIC", "3807"],
  ["Officer",            "VIC", "3809"],
  ["Berwick",            "VIC", "3806"],
  ["Narre Warren",       "VIC", "3805"],
  ["Narre Warren North", "VIC", "3804"],
  ["Narre Warren South", "VIC", "3805"],
  ["Hampton Park",       "VIC", "3976"],
  ["Hallam",             "VIC", "3803"],
  ["Endeavour Hills",    "VIC", "3802"],
  ["Lyndhurst",          "VIC", "3975"],
  ["Lynbrook",           "VIC", "3975"],
  ["Cranbourne",         "VIC", "3977"],
  ["Cranbourne North",   "VIC", "3977"],
  ["Cranbourne East",    "VIC", "3977"],
  ["Cranbourne West",    "VIC", "3977"],
  ["Clyde",              "VIC", "3978"],
  ["Clyde North",        "VIC", "3978"],
  ["Tooradin",           "VIC", "3980"],
  ["Koo Wee Rup",        "VIC", "3981"],
  // VIC — Mornington Peninsula extras
  ["Dromana",            "VIC", "3936"],
  ["Safety Beach",       "VIC", "3936"],
  ["McCrae",             "VIC", "3938"],
  ["Capel Sound",        "VIC", "3940"],
  ["Hastings",           "VIC", "3915"],
  ["Bittern",            "VIC", "3918"],
  ["Crib Point",         "VIC", "3919"],
  ["Somers",             "VIC", "3927"],
  ["Balnarring",         "VIC", "3926"],
  ["Red Hill",           "VIC", "3937"],
  ["Flinders",           "VIC", "3929"],
  ["Cape Schanck",       "VIC", "3939"],
  ["Blairgowrie",        "VIC", "3942"],
  ["Tootgarook",         "VIC", "3941"],
  ["Portsea",            "VIC", "3944"],
  // VIC — Yarra Valley & Dandenong Ranges
  ["Lilydale",           "VIC", "3140"],
  ["Mount Evelyn",       "VIC", "3796"],
  ["Coldstream",         "VIC", "3770"],
  ["Healesville",        "VIC", "3777"],
  ["Yarra Glen",         "VIC", "3775"],
  ["Warburton",          "VIC", "3799"],
  ["Marysville",         "VIC", "3779"],
  ["Belgrave",           "VIC", "3160"],
  ["Tecoma",             "VIC", "3160"],
  ["Upwey",              "VIC", "3158"],
  ["Selby",              "VIC", "3159"],
  ["Olinda",             "VIC", "3788"],
  ["Sassafras",          "VIC", "3787"],
  ["Mount Dandenong",    "VIC", "3767"],
  ["Kallista",           "VIC", "3791"],
  ["Monbulk",            "VIC", "3793"],
  ["Emerald",            "VIC", "3782"],
  ["Cockatoo",           "VIC", "3781"],
  ["Gembrook",           "VIC", "3783"],
  // VIC — Surf Coast & Bellarine Peninsula
  ["Torquay",            "VIC", "3228"],
  ["Jan Juc",            "VIC", "3228"],
  ["Anglesea",           "VIC", "3230"],
  ["Aireys Inlet",       "VIC", "3231"],
  ["Lorne",              "VIC", "3232"],
  ["Apollo Bay",         "VIC", "3233"],
  ["Ocean Grove",        "VIC", "3226"],
  ["Barwon Heads",       "VIC", "3227"],
  ["Drysdale",           "VIC", "3222"],
  ["Clifton Springs",    "VIC", "3222"],
  ["Portarlington",      "VIC", "3223"],
  ["Indented Head",      "VIC", "3223"],
  ["St Leonards",        "VIC", "3223"],
  ["Queenscliff",        "VIC", "3225"],
  ["Point Lonsdale",     "VIC", "3225"],
  ["Leopold",            "VIC", "3224"],
  ["Lara",               "VIC", "3212"],
  ["Corio",              "VIC", "3214"],
  ["Norlane",            "VIC", "3214"],
  // VIC — Phillip Island & Bass Coast
  ["Cowes",              "VIC", "3922"],
  ["San Remo",           "VIC", "3925"],
  ["Newhaven",           "VIC", "3925"],
  ["Rhyll",              "VIC", "3923"],
  ["Inverloch",          "VIC", "3996"],
  ["Wonthaggi",          "VIC", "3995"],
  ["Cape Paterson",      "VIC", "3995"],
  // VIC — Gippsland
  ["Drouin",             "VIC", "3818"],
  ["Warragul",           "VIC", "3820"],
  ["Trafalgar",          "VIC", "3824"],
  ["Leongatha",          "VIC", "3953"],
  ["Korumburra",         "VIC", "3950"],
  ["Foster",             "VIC", "3960"],
  ["Yarram",             "VIC", "3971"],
  ["Maffra",             "VIC", "3860"],
  ["Stratford",          "VIC", "3862"],
  ["Bairnsdale",         "VIC", "3875"],
  ["Lakes Entrance",     "VIC", "3909"],
  ["Paynesville",        "VIC", "3880"],
  ["Orbost",             "VIC", "3888"],
  ["Mallacoota",         "VIC", "3892"],
  // VIC — Macedon Ranges & Goldfields
  ["Sunbury",            "VIC", "3429"],
  ["Macedon",            "VIC", "3440"],
  ["Mount Macedon",      "VIC", "3441"],
  ["Woodend",            "VIC", "3442"],
  ["Gisborne",           "VIC", "3437"],
  ["New Gisborne",       "VIC", "3438"],
  ["Riddells Creek",     "VIC", "3431"],
  ["Romsey",             "VIC", "3434"],
  ["Lancefield",         "VIC", "3435"],
  ["Kyneton",            "VIC", "3444"],
  ["Castlemaine",        "VIC", "3450"],
  ["Maldon",             "VIC", "3463"],
  ["Maryborough",        "VIC", "3465"],
  ["Daylesford",         "VIC", "3460"],
  ["Hepburn Springs",    "VIC", "3461"],
  ["Trentham",           "VIC", "3458"],
  ["Creswick",           "VIC", "3363"],
  ["Bacchus Marsh",      "VIC", "3340"],
  ["Ballan",             "VIC", "3342"],
  // VIC — North-East
  ["Mansfield",          "VIC", "3722"],
  ["Bright",             "VIC", "3741"],
  ["Beechworth",         "VIC", "3747"],
  ["Yackandandah",       "VIC", "3749"],
  ["Rutherglen",         "VIC", "3685"],
  ["Chiltern",           "VIC", "3683"],
  ["Tallangatta",        "VIC", "3700"],
  ["Corryong",           "VIC", "3707"],
  ["Myrtleford",         "VIC", "3737"],
  ["Mount Beauty",       "VIC", "3699"],
  ["Benalla",            "VIC", "3672"],
  ["Euroa",              "VIC", "3666"],
  // VIC — Goulburn & North Central
  ["Seymour",            "VIC", "3660"],
  ["Yea",                "VIC", "3717"],
  ["Alexandra",          "VIC", "3714"],
  ["Kilmore",            "VIC", "3764"],
  ["Wallan",             "VIC", "3756"],
  ["Beveridge",          "VIC", "3753"],
  ["Broadford",          "VIC", "3658"],
  ["Numurkah",           "VIC", "3636"],
  ["Cobram",             "VIC", "3644"],
  ["Yarrawonga",         "VIC", "3730"],
  ["Rochester",          "VIC", "3561"],
  ["Kyabram",            "VIC", "3620"],
  ["Tatura",             "VIC", "3616"],
  ["Nagambie",           "VIC", "3608"],
  // VIC — Outer North & West Growth
  ["Craigieburn",        "VIC", "3064"],
  ["Mickleham",          "VIC", "3064"],
  ["Donnybrook",         "VIC", "3064"],
  ["Greenvale",          "VIC", "3059"],
  ["Roxburgh Park",      "VIC", "3064"],
  ["Melton",             "VIC", "3337"],
  ["Melton South",       "VIC", "3338"],
  ["Melton West",        "VIC", "3337"],
  ["Caroline Springs",   "VIC", "3023"],
  ["Burnside Heights",   "VIC", "3023"],
  ["Hillside",           "VIC", "3037"],
  ["Taylors Hill",       "VIC", "3037"],
  ["Taylors Lakes",      "VIC", "3038"],
  ["Sydenham",           "VIC", "3037"],
  ["Keilor",             "VIC", "3036"],
  ["Keilor East",        "VIC", "3033"],
  ["Keilor Downs",       "VIC", "3038"],
  // VIC — Wimmera & Western Districts
  ["Ararat",             "VIC", "3377"],
  ["Stawell",            "VIC", "3380"],
  ["Halls Gap",          "VIC", "3381"],
  ["Dimboola",           "VIC", "3414"],
  ["Nhill",              "VIC", "3418"],
  ["Warracknabeal",      "VIC", "3393"],
  ["Camperdown",         "VIC", "3260"],
  ["Colac",              "VIC", "3250"],
  ["Terang",             "VIC", "3264"],
  ["Cobden",             "VIC", "3266"],
  ["Hamilton",           "VIC", "3300"],
  ["Portland",           "VIC", "3305"],
  ["Heywood",            "VIC", "3304"],
  ["Casterton",          "VIC", "3311"],

  // NSW — Sydney CBD & surrounds
  ["Sydney",             "NSW", "2000"],
  ["Haymarket",          "NSW", "2000"],
  ["Pyrmont",            "NSW", "2009"],
  ["Ultimo",             "NSW", "2007"],
  ["Glebe",              "NSW", "2037"],
  ["Forest Lodge",       "NSW", "2037"],
  ["Annandale",          "NSW", "2038"],
  ["Balmain",            "NSW", "2041"],
  ["Rozelle",            "NSW", "2039"],
  ["Leichhardt",         "NSW", "2040"],
  // NSW — Inner East
  ["Surry Hills",        "NSW", "2010"],
  ["Darlinghurst",       "NSW", "2010"],
  ["Potts Point",        "NSW", "2011"],
  ["Elizabeth Bay",      "NSW", "2011"],
  ["Woolloomooloo",      "NSW", "2011"],
  ["Paddington",         "NSW", "2021"],
  ["Woollahra",          "NSW", "2025"],
  ["Edgecliff",          "NSW", "2027"],
  ["Double Bay",         "NSW", "2028"],
  ["Rose Bay",           "NSW", "2029"],
  ["Bellevue Hill",      "NSW", "2023"],
  ["Vaucluse",           "NSW", "2030"],
  ["Watsons Bay",        "NSW", "2030"],
  ["Bondi",              "NSW", "2026"],
  ["Bondi Beach",        "NSW", "2026"],
  ["Bondi Junction",     "NSW", "2022"],
  ["Bronte",             "NSW", "2024"],
  ["Coogee",             "NSW", "2034"],
  ["Randwick",           "NSW", "2031"],
  ["Kensington",         "NSW", "2033"],
  ["Kingsford",          "NSW", "2032"],
  // NSW — Inner West
  ["Newtown",            "NSW", "2042"],
  ["Erskineville",       "NSW", "2043"],
  ["Redfern",            "NSW", "2016"],
  ["Waterloo",           "NSW", "2017"],
  ["Alexandria",         "NSW", "2015"],
  ["Zetland",            "NSW", "2017"],
  ["Marrickville",       "NSW", "2204"],
  ["Dulwich Hill",       "NSW", "2203"],
  ["Stanmore",           "NSW", "2048"],
  ["Petersham",          "NSW", "2049"],
  ["Enmore",             "NSW", "2042"],
  // NSW — North Shore
  ["North Sydney",       "NSW", "2060"],
  ["Milsons Point",      "NSW", "2061"],
  ["Kirribilli",         "NSW", "2061"],
  ["Neutral Bay",        "NSW", "2089"],
  ["Cremorne",           "NSW", "2090"],
  ["Mosman",             "NSW", "2088"],
  ["Crows Nest",         "NSW", "2065"],
  ["St Leonards",        "NSW", "2065"],
  ["Artarmon",           "NSW", "2064"],
  ["Willoughby",         "NSW", "2068"],
  ["Chatswood",          "NSW", "2067"],
  ["Lane Cove",          "NSW", "2066"],
  ["Longueville",        "NSW", "2066"],
  ["Manly",              "NSW", "2095"],
  ["Manly Vale",         "NSW", "2093"],
  ["Freshwater",         "NSW", "2096"],
  ["Dee Why",            "NSW", "2099"],
  ["Collaroy",           "NSW", "2097"],
  ["Narrabeen",          "NSW", "2101"],
  ["Mona Vale",          "NSW", "2103"],
  ["Avalon Beach",       "NSW", "2107"],
  ["Palm Beach",         "NSW", "2108"],
  // NSW — Upper North Shore
  ["Gordon",             "NSW", "2072"],
  ["Killara",            "NSW", "2071"],
  ["Lindfield",          "NSW", "2070"],
  ["Roseville",          "NSW", "2069"],
  ["St Ives",            "NSW", "2075"],
  ["Turramurra",         "NSW", "2074"],
  ["Wahroonga",          "NSW", "2076"],
  ["Hornsby",            "NSW", "2077"],
  ["Pymble",             "NSW", "2073"],
  // NSW — Western Sydney
  ["Parramatta",         "NSW", "2150"],
  ["Granville",          "NSW", "2142"],
  ["Westmead",           "NSW", "2145"],
  ["Merrylands",         "NSW", "2160"],
  ["Guildford",          "NSW", "2161"],
  ["Auburn",             "NSW", "2144"],
  ["Lidcombe",           "NSW", "2141"],
  ["Homebush",           "NSW", "2140"],
  ["Strathfield",        "NSW", "2135"],
  ["Burwood",            "NSW", "2134"],
  ["Croydon",            "NSW", "2132"],
  ["Ashfield",           "NSW", "2131"],
  ["Liverpool",          "NSW", "2170"],
  ["Campbelltown",       "NSW", "2560"],
  ["Penrith",            "NSW", "2750"],
  ["Blacktown",          "NSW", "2148"],
  ["Seven Hills",        "NSW", "2147"],
  ["Baulkham Hills",     "NSW", "2153"],
  ["Castle Hill",        "NSW", "2154"],
  ["Kellyville",         "NSW", "2155"],
  ["Rouse Hill",         "NSW", "2155"],
  ["Richmond",           "NSW", "2753"],
  // NSW — Regional
  ["Newcastle",          "NSW", "2300"],
  ["Hamilton",           "NSW", "2303"],
  ["Maitland",           "NSW", "2320"],
  ["Cessnock",           "NSW", "2325"],
  ["Charlestown",        "NSW", "2290"],
  ["Warners Bay",        "NSW", "2282"],
  ["Wollongong",         "NSW", "2500"],
  ["Figtree",            "NSW", "2525"],
  ["Shellharbour",       "NSW", "2529"],
  ["Kiama",              "NSW", "2533"],
  ["Nowra",              "NSW", "2541"],
  ["Batemans Bay",       "NSW", "2536"],
  ["Coffs Harbour",      "NSW", "2450"],
  ["Port Macquarie",     "NSW", "2444"],
  ["Tamworth",           "NSW", "2340"],
  ["Armidale",           "NSW", "2350"],
  ["Dubbo",              "NSW", "2830"],
  ["Orange",             "NSW", "2800"],
  ["Bathurst",           "NSW", "2795"],
  ["Wagga Wagga",        "NSW", "2650"],
  ["Albury",             "NSW", "2640"],
  ["Queanbeyan",         "NSW", "2620"],
  // NSW — Northern Rivers & Far North Coast
  ["Lismore",            "NSW", "2480"],
  ["Ballina",            "NSW", "2478"],
  ["Byron Bay",          "NSW", "2481"],
  ["Mullumbimby",        "NSW", "2482"],
  ["Brunswick Heads",    "NSW", "2483"],
  ["Ocean Shores",       "NSW", "2483"],
  ["Casino",             "NSW", "2470"],
  ["Kyogle",             "NSW", "2474"],
  ["Alstonville",        "NSW", "2477"],
  ["Lennox Head",        "NSW", "2478"],
  ["Tweed Heads",        "NSW", "2485"],
  ["Kingscliff",         "NSW", "2487"],
  ["Pottsville",         "NSW", "2489"],
  ["Murwillumbah",       "NSW", "2484"],
  ["Cabarita Beach",     "NSW", "2488"],
  // NSW — Mid-North Coast
  ["Grafton",            "NSW", "2460"],
  ["Yamba",              "NSW", "2464"],
  ["Maclean",            "NSW", "2463"],
  ["Iluka",              "NSW", "2466"],
  ["Sawtell",            "NSW", "2452"],
  ["Woolgoolga",         "NSW", "2456"],
  ["Bellingen",          "NSW", "2454"],
  ["Nambucca Heads",     "NSW", "2448"],
  ["Macksville",         "NSW", "2447"],
  ["Kempsey",            "NSW", "2440"],
  ["Crescent Head",      "NSW", "2440"],
  ["South West Rocks",   "NSW", "2431"],
  ["Wauchope",           "NSW", "2446"],
  ["Laurieton",          "NSW", "2443"],
  ["Forster",            "NSW", "2428"],
  ["Tuncurry",           "NSW", "2428"],
  ["Taree",              "NSW", "2430"],
  ["Wingham",            "NSW", "2429"],
  ["Old Bar",            "NSW", "2430"],
  // NSW — Hunter & Port Stephens
  ["Singleton",          "NSW", "2330"],
  ["Muswellbrook",       "NSW", "2333"],
  ["Scone",              "NSW", "2337"],
  ["Aberdeen",           "NSW", "2336"],
  ["Denman",             "NSW", "2328"],
  ["Nelson Bay",         "NSW", "2315"],
  ["Anna Bay",           "NSW", "2316"],
  ["Soldiers Point",     "NSW", "2317"],
  ["Salamander Bay",     "NSW", "2317"],
  ["Tea Gardens",        "NSW", "2324"],
  ["Stockton",           "NSW", "2295"],
  ["Mayfield",           "NSW", "2304"],
  ["Adamstown",          "NSW", "2289"],
  ["Belmont",            "NSW", "2280"],
  ["Swansea",            "NSW", "2281"],
  ["Toronto",            "NSW", "2283"],
  // NSW — Central Coast
  ["Gosford",            "NSW", "2250"],
  ["Erina",              "NSW", "2250"],
  ["Terrigal",           "NSW", "2260"],
  ["Avoca Beach",        "NSW", "2251"],
  ["Wamberal",           "NSW", "2260"],
  ["The Entrance",       "NSW", "2261"],
  ["Long Jetty",         "NSW", "2261"],
  ["Tuggerah",           "NSW", "2259"],
  ["Wyong",              "NSW", "2259"],
  ["Woy Woy",            "NSW", "2256"],
  ["Ettalong Beach",     "NSW", "2257"],
  ["Umina Beach",        "NSW", "2257"],
  // NSW — Blue Mountains
  ["Springwood",         "NSW", "2777"],
  ["Glenbrook",          "NSW", "2773"],
  ["Blaxland",           "NSW", "2774"],
  ["Faulconbridge",      "NSW", "2776"],
  ["Wentworth Falls",    "NSW", "2782"],
  ["Leura",              "NSW", "2780"],
  ["Katoomba",           "NSW", "2780"],
  ["Blackheath",         "NSW", "2785"],
  ["Mount Victoria",     "NSW", "2786"],
  ["Lithgow",            "NSW", "2790"],
  ["Oberon",             "NSW", "2787"],
  // NSW — Southern Highlands
  ["Bowral",             "NSW", "2576"],
  ["Mittagong",          "NSW", "2575"],
  ["Moss Vale",          "NSW", "2577"],
  ["Bundanoon",          "NSW", "2578"],
  ["Robertson",          "NSW", "2577"],
  ["Berrima",            "NSW", "2577"],
  // NSW — South Coast
  ["Berry",              "NSW", "2535"],
  ["Huskisson",          "NSW", "2540"],
  ["Vincentia",          "NSW", "2540"],
  ["Sussex Inlet",       "NSW", "2540"],
  ["Ulladulla",          "NSW", "2539"],
  ["Mollymook",          "NSW", "2539"],
  ["Milton",             "NSW", "2538"],
  ["Moruya",             "NSW", "2537"],
  ["Tuross Head",        "NSW", "2537"],
  ["Narooma",            "NSW", "2546"],
  ["Bermagui",           "NSW", "2546"],
  ["Tathra",             "NSW", "2550"],
  ["Bega",               "NSW", "2550"],
  ["Merimbula",          "NSW", "2548"],
  ["Eden",               "NSW", "2551"],
  ["Pambula",            "NSW", "2549"],
  // NSW — Snowy Mountains
  ["Cooma",              "NSW", "2630"],
  ["Jindabyne",          "NSW", "2627"],
  ["Berridale",          "NSW", "2628"],
  ["Thredbo",            "NSW", "2625"],
  // NSW — Riverina
  ["Griffith",           "NSW", "2680"],
  ["Leeton",             "NSW", "2705"],
  ["Narrandera",         "NSW", "2700"],
  ["Hay",                "NSW", "2711"],
  ["Deniliquin",         "NSW", "2710"],
  ["Tocumwal",           "NSW", "2714"],
  ["Corowa",             "NSW", "2646"],
  ["Howlong",            "NSW", "2643"],
  ["Holbrook",           "NSW", "2644"],
  ["Tumut",              "NSW", "2720"],
  ["Gundagai",           "NSW", "2722"],
  ["Junee",              "NSW", "2663"],
  ["Cootamundra",        "NSW", "2590"],
  ["Temora",             "NSW", "2666"],
  ["West Wyalong",       "NSW", "2671"],
  // NSW — Central West
  ["Cowra",              "NSW", "2794"],
  ["Forbes",             "NSW", "2871"],
  ["Parkes",             "NSW", "2870"],
  ["Mudgee",             "NSW", "2850"],
  ["Gulgong",            "NSW", "2852"],
  ["Wellington",         "NSW", "2820"],
  ["Coonabarabran",      "NSW", "2357"],
  // NSW — New England
  ["Inverell",           "NSW", "2360"],
  ["Glen Innes",         "NSW", "2370"],
  ["Tenterfield",        "NSW", "2372"],
  ["Quirindi",           "NSW", "2343"],
  ["Gunnedah",           "NSW", "2380"],
  ["Narrabri",           "NSW", "2390"],
  ["Moree",              "NSW", "2400"],
  ["Walcha",             "NSW", "2354"],
  // NSW — Far West
  ["Bourke",             "NSW", "2840"],
  ["Cobar",              "NSW", "2835"],
  ["Lightning Ridge",    "NSW", "2834"],
  ["Walgett",            "NSW", "2832"],
  ["Broken Hill",        "NSW", "2880"],
  ["Wilcannia",          "NSW", "2836"],
  ["Menindee",           "NSW", "2879"],

  // QLD — Brisbane CBD & inner
  ["Brisbane City",      "QLD", "4000"],
  ["South Brisbane",     "QLD", "4101"],
  ["West End",           "QLD", "4101"],
  ["Woolloongabba",      "QLD", "4102"],
  ["Spring Hill",        "QLD", "4004"],
  ["Fortitude Valley",   "QLD", "4006"],
  ["New Farm",           "QLD", "4005"],
  ["Newstead",           "QLD", "4006"],
  ["Teneriffe",          "QLD", "4005"],
  ["Paddington",         "QLD", "4064"],
  ["Red Hill",           "QLD", "4059"],
  ["Bardon",             "QLD", "4065"],
  ["Ashgrove",           "QLD", "4060"],
  ["Kelvin Grove",       "QLD", "4059"],
  ["Herston",            "QLD", "4006"],
  ["Lutwyche",           "QLD", "4030"],
  ["Windsor",            "QLD", "4030"],
  ["Clayfield",          "QLD", "4011"],
  ["Ascot",              "QLD", "4007"],
  ["Hamilton",           "QLD", "4007"],
  ["Albion",             "QLD", "4010"],
  ["Bowen Hills",        "QLD", "4006"],
  // QLD — South Brisbane
  ["Annerley",           "QLD", "4103"],
  ["Moorooka",           "QLD", "4105"],
  ["Salisbury",          "QLD", "4107"],
  ["Sunnybank",          "QLD", "4109"],
  ["Sunnybank Hills",    "QLD", "4109"],
  ["Carindale",          "QLD", "4152"],
  ["Carina",             "QLD", "4152"],
  ["Camp Hill",          "QLD", "4152"],
  ["Holland Park",       "QLD", "4121"],
  ["Greenslopes",        "QLD", "4120"],
  ["Coorparoo",          "QLD", "4151"],
  ["East Brisbane",      "QLD", "4169"],
  ["Norman Park",        "QLD", "4170"],
  // QLD — North Brisbane
  ["Chermside",          "QLD", "4032"],
  ["Aspley",             "QLD", "4034"],
  ["Stafford",           "QLD", "4053"],
  ["Wavell Heights",     "QLD", "4012"],
  ["Nundah",             "QLD", "4012"],
  ["Northgate",          "QLD", "4013"],
  ["Sandgate",           "QLD", "4017"],
  ["Bracken Ridge",      "QLD", "4017"],
  // QLD — West Brisbane
  ["Kenmore",            "QLD", "4069"],
  ["Chapel Hill",        "QLD", "4069"],
  ["Indooroopilly",      "QLD", "4068"],
  ["Toowong",            "QLD", "4066"],
  ["Auchenflower",       "QLD", "4066"],
  ["Milton",             "QLD", "4064"],
  // QLD — Ipswich
  ["Ipswich",            "QLD", "4305"],
  // QLD — Gold Coast
  ["Surfers Paradise",   "QLD", "4217"],
  ["Broadbeach",         "QLD", "4218"],
  ["Mermaid Beach",      "QLD", "4218"],
  ["Burleigh Heads",     "QLD", "4220"],
  ["Robina",             "QLD", "4226"],
  ["Varsity Lakes",      "QLD", "4227"],
  ["Mudgeeraba",         "QLD", "4213"],
  ["Nerang",             "QLD", "4211"],
  ["Southport",          "QLD", "4215"],
  ["Main Beach",         "QLD", "4217"],
  ["Labrador",           "QLD", "4215"],
  ["Parkwood",           "QLD", "4214"],
  ["Helensvale",         "QLD", "4212"],
  ["Hope Island",        "QLD", "4212"],
  ["Coomera",            "QLD", "4209"],
  ["Pimpama",            "QLD", "4209"],
  // QLD — Sunshine Coast
  ["Noosa Heads",        "QLD", "4567"],
  ["Noosaville",         "QLD", "4566"],
  ["Tewantin",           "QLD", "4565"],
  ["Buderim",            "QLD", "4556"],
  ["Mooloolaba",         "QLD", "4557"],
  ["Maroochydore",       "QLD", "4558"],
  ["Nambour",            "QLD", "4560"],
  ["Caloundra",          "QLD", "4551"],
  ["Kawana Waters",      "QLD", "4575"],
  ["Sippy Downs",        "QLD", "4556"],
  // QLD — Regional
  ["Toowoomba",          "QLD", "4350"],
  ["Cairns",             "QLD", "4870"],
  ["Townsville",         "QLD", "4810"],
  ["Rockhampton",        "QLD", "4700"],
  ["Mackay",             "QLD", "4740"],
  ["Bundaberg",          "QLD", "4670"],
  ["Hervey Bay",         "QLD", "4655"],
  ["Gladstone",          "QLD", "4680"],
  // QLD — Bayside Brisbane / Redlands
  ["Cleveland",          "QLD", "4163"],
  ["Capalaba",           "QLD", "4157"],
  ["Wynnum",             "QLD", "4178"],
  ["Manly",              "QLD", "4179"],
  ["Wakerley",           "QLD", "4154"],
  ["Birkdale",           "QLD", "4159"],
  ["Alexandra Hills",    "QLD", "4161"],
  ["Thornlands",         "QLD", "4164"],
  ["Victoria Point",     "QLD", "4165"],
  ["Redland Bay",        "QLD", "4165"],
  ["Ormiston",           "QLD", "4160"],
  ["Wellington Point",   "QLD", "4160"],
  // QLD — Logan
  ["Beenleigh",          "QLD", "4207"],
  ["Springwood",         "QLD", "4127"],
  ["Logan Central",      "QLD", "4114"],
  ["Daisy Hill",         "QLD", "4127"],
  ["Loganholme",         "QLD", "4129"],
  ["Eight Mile Plains",  "QLD", "4113"],
  ["Slacks Creek",       "QLD", "4127"],
  ["Underwood",          "QLD", "4119"],
  ["Browns Plains",      "QLD", "4118"],
  ["Marsden",            "QLD", "4132"],
  ["Kingston",           "QLD", "4114"],
  ["Woodridge",          "QLD", "4114"],
  // QLD — Moreton Bay
  ["Caboolture",         "QLD", "4510"],
  ["Morayfield",         "QLD", "4506"],
  ["Burpengary",         "QLD", "4505"],
  ["Narangba",           "QLD", "4504"],
  ["North Lakes",        "QLD", "4509"],
  ["Mango Hill",         "QLD", "4509"],
  ["Redcliffe",          "QLD", "4020"],
  ["Margate",            "QLD", "4019"],
  ["Scarborough",        "QLD", "4020"],
  ["Kippa-Ring",         "QLD", "4021"],
  ["Strathpine",         "QLD", "4500"],
  ["Petrie",             "QLD", "4502"],
  ["Lawnton",            "QLD", "4501"],
  ["Bray Park",          "QLD", "4500"],
  // QLD — Ipswich extras
  ["Springfield",        "QLD", "4300"],
  ["Springfield Lakes",  "QLD", "4300"],
  ["Goodna",             "QLD", "4300"],
  ["Booval",             "QLD", "4304"],
  ["Bundamba",           "QLD", "4304"],
  // QLD — Toowoomba & Darling Downs
  ["Highfields",         "QLD", "4352"],
  ["Crows Nest",         "QLD", "4355"],
  ["Pittsworth",         "QLD", "4356"],
  ["Stanthorpe",         "QLD", "4380"],
  ["Warwick",            "QLD", "4370"],
  ["Dalby",              "QLD", "4405"],
  ["Chinchilla",         "QLD", "4413"],
  ["Goondiwindi",        "QLD", "4390"],
  ["Kingaroy",           "QLD", "4610"],
  ["Roma",               "QLD", "4455"],
  ["Charleville",        "QLD", "4470"],
  // QLD — Wide Bay
  ["Maryborough",        "QLD", "4650"],
  ["Childers",           "QLD", "4660"],
  ["Tin Can Bay",        "QLD", "4580"],
  ["Rainbow Beach",      "QLD", "4581"],
  ["Gympie",             "QLD", "4570"],
  // QLD — Central Queensland
  ["Yeppoon",            "QLD", "4703"],
  ["Tannum Sands",       "QLD", "4680"],
  ["Boyne Island",       "QLD", "4680"],
  ["Calliope",           "QLD", "4680"],
  ["Emerald",            "QLD", "4720"],
  ["Blackwater",         "QLD", "4717"],
  // QLD — Mackay-Whitsunday
  ["Sarina",             "QLD", "4737"],
  ["Walkerston",         "QLD", "4751"],
  ["Proserpine",         "QLD", "4800"],
  ["Airlie Beach",       "QLD", "4802"],
  ["Cannonvale",         "QLD", "4802"],
  ["Bowen",              "QLD", "4805"],
  // QLD — North Queensland
  ["Charters Towers",    "QLD", "4820"],
  ["Ayr",                "QLD", "4807"],
  ["Home Hill",          "QLD", "4806"],
  ["Ingham",             "QLD", "4850"],
  ["Tully",              "QLD", "4854"],
  ["Innisfail",          "QLD", "4860"],
  ["Mission Beach",      "QLD", "4852"],
  ["Edmonton",           "QLD", "4869"],
  ["Gordonvale",         "QLD", "4865"],
  ["Mareeba",            "QLD", "4880"],
  ["Atherton",           "QLD", "4883"],
  ["Yungaburra",         "QLD", "4884"],
  ["Malanda",            "QLD", "4885"],
  ["Ravenshoe",          "QLD", "4888"],
  ["Kuranda",            "QLD", "4881"],
  ["Port Douglas",       "QLD", "4877"],
  ["Mossman",            "QLD", "4873"],
  ["Cooktown",           "QLD", "4895"],
  ["Mount Isa",          "QLD", "4825"],
  ["Cloncurry",          "QLD", "4824"],
  // QLD — Sunshine Coast hinterland
  ["Maleny",             "QLD", "4552"],
  ["Montville",          "QLD", "4560"],
  ["Mapleton",           "QLD", "4560"],
  ["Eumundi",            "QLD", "4562"],
  ["Cooroy",             "QLD", "4563"],
  ["Pomona",             "QLD", "4568"],
  ["Yandina",            "QLD", "4561"],
  ["Beerwah",            "QLD", "4519"],
  ["Glass House Mountains", "QLD", "4518"],
  // QLD — Outback
  ["Longreach",          "QLD", "4730"],
  ["Winton",             "QLD", "4735"],
  ["Barcaldine",         "QLD", "4725"],
  ["Blackall",           "QLD", "4472"],

  // SA — Adelaide
  ["Adelaide",           "SA",  "5000"],
  ["North Adelaide",     "SA",  "5006"],
  ["Norwood",            "SA",  "5067"],
  ["Rose Park",          "SA",  "5067"],
  ["Parkside",           "SA",  "5063"],
  ["Unley",              "SA",  "5061"],
  ["Malvern",            "SA",  "5061"],
  ["Burnside",           "SA",  "5066"],
  ["Glenside",           "SA",  "5065"],
  ["Mitcham",            "SA",  "5062"],
  ["Black Forest",       "SA",  "5035"],
  ["Prospect",           "SA",  "5082"],
  ["Nailsworth",         "SA",  "5083"],
  ["Blair Athol",        "SA",  "5084"],
  ["Enfield",            "SA",  "5085"],
  ["Gepps Cross",        "SA",  "5094"],
  ["Mawson Lakes",       "SA",  "5095"],
  ["Salisbury",          "SA",  "5108"],
  ["Elizabeth",          "SA",  "5112"],
  ["Marion",             "SA",  "5043"],
  ["Oaklands Park",      "SA",  "5046"],
  ["Plympton",           "SA",  "5038"],
  ["Mile End",           "SA",  "5031"],
  ["Thebarton",          "SA",  "5031"],
  ["Henley Beach",       "SA",  "5022"],
  ["Glenelg",            "SA",  "5045"],
  ["Brighton",           "SA",  "5048"],
  ["Hallett Cove",       "SA",  "5158"],
  ["Christies Beach",    "SA",  "5165"],
  ["Noarlunga",          "SA",  "5168"],
  ["McLaren Vale",       "SA",  "5171"],
  ["Glen Osmond",        "SA",  "5064"],
  ["Dulwich",            "SA",  "5065"],
  ["Aldgate",            "SA",  "5154"],
  ["Stirling",           "SA",  "5152"],
  ["Crafers",            "SA",  "5152"],
  ["Hahndorf",           "SA",  "5245"],
  ["Mount Gambier",      "SA",  "5290"],
  ["Whyalla",            "SA",  "5600"],
  ["Port Augusta",       "SA",  "5700"],
  ["Port Pirie",         "SA",  "5540"],
  ["Victor Harbor",      "SA",  "5211"],
  ["Murray Bridge",      "SA",  "5253"],
  // SA — Adelaide Hills
  ["Bridgewater",        "SA",  "5155"],
  ["Heathfield",         "SA",  "5153"],
  ["Mylor",              "SA",  "5153"],
  ["Echunga",            "SA",  "5153"],
  ["Macclesfield",       "SA",  "5153"],
  ["Meadows",            "SA",  "5201"],
  ["Mount Pleasant",     "SA",  "5235"],
  ["Birdwood",           "SA",  "5234"],
  ["Lobethal",           "SA",  "5241"],
  ["Woodside",           "SA",  "5244"],
  ["Gumeracha",          "SA",  "5233"],
  ["Williamstown",       "SA",  "5351"],
  // SA — Northern Adelaide
  ["Gawler",             "SA",  "5118"],
  ["Munno Para",         "SA",  "5115"],
  ["Smithfield",         "SA",  "5114"],
  ["Andrews Farm",       "SA",  "5114"],
  ["Blakeview",          "SA",  "5114"],
  ["Para Hills",         "SA",  "5096"],
  ["Modbury",            "SA",  "5092"],
  ["Ingle Farm",         "SA",  "5098"],
  ["Pooraka",            "SA",  "5095"],
  ["Tea Tree Gully",     "SA",  "5091"],
  ["Golden Grove",       "SA",  "5125"],
  ["Wynn Vale",          "SA",  "5127"],
  ["Surrey Downs",       "SA",  "5126"],
  ["Walkerville",        "SA",  "5081"],
  ["Klemzig",            "SA",  "5087"],
  ["Highbury",           "SA",  "5089"],
  // SA — Western & Coastal
  ["Grange",             "SA",  "5022"],
  ["Tennyson",           "SA",  "5022"],
  ["Semaphore",          "SA",  "5019"],
  ["Largs Bay",          "SA",  "5016"],
  ["Largs North",        "SA",  "5016"],
  ["Osborne",            "SA",  "5017"],
  ["Outer Harbor",       "SA",  "5018"],
  ["Birkenhead",         "SA",  "5015"],
  ["Port Adelaide",      "SA",  "5015"],
  ["West Lakes",         "SA",  "5021"],
  ["West Beach",         "SA",  "5024"],
  ["Henley Beach South", "SA",  "5022"],
  ["Findon",             "SA",  "5023"],
  ["Beverley",           "SA",  "5009"],
  ["Kidman Park",        "SA",  "5025"],
  ["Fulham Gardens",     "SA",  "5024"],
  // SA — Southern
  ["Aberfoyle Park",     "SA",  "5159"],
  ["Happy Valley",       "SA",  "5159"],
  ["Reynella",           "SA",  "5161"],
  ["Morphett Vale",      "SA",  "5162"],
  ["Hackham",            "SA",  "5163"],
  ["Old Noarlunga",      "SA",  "5168"],
  ["Port Noarlunga",     "SA",  "5167"],
  ["Seaford",            "SA",  "5169"],
  ["Aldinga Beach",      "SA",  "5173"],
  ["Sellicks Beach",     "SA",  "5174"],
  ["Maslin Beach",       "SA",  "5170"],
  ["Willunga",           "SA",  "5172"],
  ["Goolwa",             "SA",  "5214"],
  ["Yankalilla",         "SA",  "5203"],
  ["Normanville",        "SA",  "5204"],
  // SA — Barossa Valley
  ["Tanunda",            "SA",  "5352"],
  ["Nuriootpa",          "SA",  "5355"],
  ["Angaston",           "SA",  "5353"],
  ["Lyndoch",            "SA",  "5351"],
  ["Greenock",           "SA",  "5360"],
  ["Truro",              "SA",  "5356"],
  ["Kapunda",            "SA",  "5373"],
  // SA — Mid North & Yorke Peninsula
  ["Clare",              "SA",  "5453"],
  ["Burra",              "SA",  "5417"],
  ["Riverton",           "SA",  "5412"],
  ["Auburn",             "SA",  "5451"],
  ["Kadina",             "SA",  "5554"],
  ["Wallaroo",           "SA",  "5556"],
  ["Moonta",             "SA",  "5558"],
  ["Maitland",           "SA",  "5573"],
  ["Minlaton",           "SA",  "5575"],
  ["Yorketown",          "SA",  "5576"],
  // SA — Eyre Peninsula & Riverland
  ["Port Lincoln",       "SA",  "5606"],
  ["Tumby Bay",          "SA",  "5605"],
  ["Streaky Bay",        "SA",  "5680"],
  ["Ceduna",             "SA",  "5690"],
  ["Cleve",              "SA",  "5640"],
  ["Cowell",             "SA",  "5602"],
  ["Berri",              "SA",  "5343"],
  ["Renmark",            "SA",  "5341"],
  ["Loxton",             "SA",  "5333"],
  ["Waikerie",           "SA",  "5330"],
  ["Barmera",            "SA",  "5345"],
  // SA — Limestone Coast & Outback
  ["Naracoorte",         "SA",  "5271"],
  ["Penola",             "SA",  "5277"],
  ["Bordertown",         "SA",  "5268"],
  ["Robe",               "SA",  "5276"],
  ["Beachport",          "SA",  "5280"],
  ["Kingston SE",        "SA",  "5275"],
  ["Millicent",          "SA",  "5280"],
  ["Tailem Bend",        "SA",  "5260"],
  ["Meningie",           "SA",  "5264"],
  ["Coober Pedy",        "SA",  "5723"],
  ["Roxby Downs",        "SA",  "5725"],
  ["Andamooka",          "SA",  "5722"],
  ["Woomera",            "SA",  "5720"],

  // WA — Perth
  ["Perth",              "WA",  "6000"],
  ["Northbridge",        "WA",  "6003"],
  ["East Perth",         "WA",  "6004"],
  ["West Perth",         "WA",  "6005"],
  ["Subiaco",            "WA",  "6008"],
  ["Cottesloe",          "WA",  "6011"],
  ["Claremont",          "WA",  "6010"],
  ["Nedlands",           "WA",  "6009"],
  ["Dalkeith",           "WA",  "6009"],
  ["Applecross",         "WA",  "6153"],
  ["South Perth",        "WA",  "6151"],
  ["Como",               "WA",  "6152"],
  ["Victoria Park",      "WA",  "6100"],
  ["Burswood",           "WA",  "6100"],
  ["Rivervale",          "WA",  "6103"],
  ["Belmont",            "WA",  "6104"],
  ["Joondalup",          "WA",  "6027"],
  ["Wanneroo",           "WA",  "6065"],
  ["Ellenbrook",         "WA",  "6069"],
  ["Midland",            "WA",  "6056"],
  ["Kalamunda",          "WA",  "6076"],
  ["Mundaring",          "WA",  "6073"],
  ["Fremantle",          "WA",  "6160"],
  ["North Fremantle",    "WA",  "6159"],
  ["Bibra Lake",         "WA",  "6163"],
  ["Hamilton Hill",      "WA",  "6163"],
  ["Coogee",             "WA",  "6166"],
  ["Rockingham",         "WA",  "6168"],
  ["Mandurah",           "WA",  "6210"],
  ["Baldivis",           "WA",  "6171"],
  ["Scarborough",        "WA",  "6019"],
  ["Wembley",            "WA",  "6014"],
  ["Floreat",            "WA",  "6014"],
  ["Churchlands",        "WA",  "6018"],
  ["Karrinyup",          "WA",  "6018"],
  ["Stirling",           "WA",  "6021"],
  ["Bunbury",            "WA",  "6230"],
  ["Geraldton",          "WA",  "6530"],
  ["Kalgoorlie",         "WA",  "6430"],
  ["Albany",             "WA",  "6330"],
  ["Broome",             "WA",  "6725"],
  ["Port Hedland",       "WA",  "6721"],
  // WA — Perth metro extras (north)
  ["Yokine",             "WA",  "6060"],
  ["Mount Hawthorn",     "WA",  "6016"],
  ["Leederville",        "WA",  "6007"],
  ["Mount Lawley",       "WA",  "6050"],
  ["Inglewood",          "WA",  "6052"],
  ["Bedford",            "WA",  "6052"],
  ["Maylands",           "WA",  "6051"],
  ["North Perth",        "WA",  "6006"],
  ["Tuart Hill",         "WA",  "6060"],
  ["Osborne Park",       "WA",  "6017"],
  ["Innaloo",            "WA",  "6018"],
  ["Doubleview",         "WA",  "6018"],
  ["Trigg",              "WA",  "6029"],
  ["Hillarys",           "WA",  "6025"],
  ["Kingsley",           "WA",  "6026"],
  ["Greenwood",          "WA",  "6024"],
  ["Padbury",            "WA",  "6025"],
  ["Mullaloo",           "WA",  "6027"],
  ["Kallaroo",           "WA",  "6025"],
  ["Craigie",            "WA",  "6025"],
  ["Edgewater",          "WA",  "6027"],
  ["Heathridge",         "WA",  "6027"],
  ["Currambine",         "WA",  "6028"],
  ["Burns Beach",        "WA",  "6028"],
  ["Ocean Reef",         "WA",  "6027"],
  ["Marmion",            "WA",  "6020"],
  ["North Beach",        "WA",  "6020"],
  ["Sorrento",           "WA",  "6020"],
  ["Connolly",           "WA",  "6027"],
  ["Quinns Rocks",       "WA",  "6030"],
  ["Mindarie",           "WA",  "6030"],
  ["Clarkson",           "WA",  "6030"],
  ["Butler",             "WA",  "6036"],
  ["Alkimos",            "WA",  "6038"],
  ["Yanchep",            "WA",  "6035"],
  ["Two Rocks",          "WA",  "6037"],
  // WA — Perth metro extras (south)
  ["Bicton",             "WA",  "6157"],
  ["Palmyra",            "WA",  "6157"],
  ["Attadale",           "WA",  "6156"],
  ["Melville",           "WA",  "6156"],
  ["Bull Creek",         "WA",  "6149"],
  ["Booragoon",          "WA",  "6154"],
  ["Brentwood",          "WA",  "6153"],
  ["Mount Pleasant",     "WA",  "6153"],
  ["Ardross",            "WA",  "6153"],
  ["Murdoch",            "WA",  "6150"],
  ["Winthrop",           "WA",  "6150"],
  ["Leeming",            "WA",  "6149"],
  ["Kardinya",           "WA",  "6163"],
  ["Cockburn Central",   "WA",  "6164"],
  ["Spearwood",          "WA",  "6163"],
  ["Atwell",             "WA",  "6164"],
  ["Aubin Grove",        "WA",  "6164"],
  ["Hammond Park",       "WA",  "6164"],
  ["Success",            "WA",  "6164"],
  ["Wellard",            "WA",  "6170"],
  ["Bertram",            "WA",  "6167"],
  ["Kwinana",            "WA",  "6167"],
  ["Hilbert",            "WA",  "6112"],
  ["Morley",             "WA",  "6062"],
  ["Noranda",            "WA",  "6062"],
  ["Dianella",           "WA",  "6059"],
  ["Beechboro",          "WA",  "6063"],
  ["Caversham",          "WA",  "6055"],
  ["Forrestfield",       "WA",  "6058"],
  ["High Wycombe",       "WA",  "6057"],
  ["Maida Vale",         "WA",  "6057"],
  ["Lesmurdie",          "WA",  "6076"],
  // WA — South West (Margaret River, Bunbury)
  ["Margaret River",     "WA",  "6285"],
  ["Busselton",          "WA",  "6280"],
  ["Dunsborough",        "WA",  "6281"],
  ["Yallingup",          "WA",  "6282"],
  ["Augusta",            "WA",  "6290"],
  ["Cowaramup",          "WA",  "6284"],
  ["Donnybrook",         "WA",  "6239"],
  ["Boyanup",            "WA",  "6237"],
  ["Capel",              "WA",  "6271"],
  ["Dalyellup",          "WA",  "6230"],
  ["Australind",         "WA",  "6233"],
  ["Eaton",              "WA",  "6232"],
  ["Harvey",             "WA",  "6220"],
  ["Pinjarra",           "WA",  "6208"],
  ["Waroona",            "WA",  "6215"],
  ["Collie",             "WA",  "6225"],
  // WA — South Coast & Goldfields
  ["Mount Barker",       "WA",  "6324"],
  ["Denmark",            "WA",  "6333"],
  ["Walpole",            "WA",  "6398"],
  ["Esperance",          "WA",  "6450"],
  ["Norseman",           "WA",  "6443"],
  ["Kambalda",           "WA",  "6442"],
  ["Coolgardie",         "WA",  "6429"],
  ["Boulder",            "WA",  "6432"],
  ["Leonora",            "WA",  "6438"],
  // WA — Wheatbelt & Mid West
  ["Northam",            "WA",  "6401"],
  ["Toodyay",            "WA",  "6566"],
  ["York",               "WA",  "6302"],
  ["Beverley",           "WA",  "6304"],
  ["Narrogin",           "WA",  "6312"],
  ["Wagin",              "WA",  "6315"],
  ["Katanning",          "WA",  "6317"],
  ["Merredin",           "WA",  "6415"],
  ["Dongara",            "WA",  "6525"],
  ["Northampton",        "WA",  "6535"],
  ["Kalbarri",           "WA",  "6536"],
  ["Denham",             "WA",  "6537"],
  ["Mount Magnet",       "WA",  "6638"],
  // WA — Pilbara & Kimberley
  ["Karratha",           "WA",  "6714"],
  ["Newman",             "WA",  "6753"],
  ["Tom Price",          "WA",  "6751"],
  ["Onslow",             "WA",  "6710"],
  ["Exmouth",            "WA",  "6707"],
  ["Carnarvon",          "WA",  "6701"],
  ["South Hedland",      "WA",  "6722"],
  ["Kununurra",          "WA",  "6743"],
  ["Wyndham",            "WA",  "6740"],
  ["Derby",              "WA",  "6728"],
  ["Halls Creek",        "WA",  "6770"],
  ["Fitzroy Crossing",   "WA",  "6765"],

  // TAS
  ["Hobart",             "TAS", "7000"],
  ["Sandy Bay",          "TAS", "7005"],
  ["Battery Point",      "TAS", "7004"],
  ["New Town",           "TAS", "7008"],
  ["Glenorchy",          "TAS", "7010"],
  ["Moonah",             "TAS", "7009"],
  ["Lindisfarne",        "TAS", "7015"],
  ["Clarence",           "TAS", "7011"],
  ["Rokeby",             "TAS", "7019"],
  ["Launceston",         "TAS", "7250"],
  ["Newnham",            "TAS", "7248"],
  ["Kings Meadows",      "TAS", "7249"],
  ["Devonport",          "TAS", "7310"],
  ["Burnie",             "TAS", "7320"],
  ["Ulverstone",         "TAS", "7315"],
  // TAS — Hobart hinterland
  ["Kingston",           "TAS", "7050"],
  ["Margate",            "TAS", "7054"],
  ["Cygnet",             "TAS", "7112"],
  ["Geeveston",          "TAS", "7116"],
  ["Huonville",          "TAS", "7109"],
  ["Dover",              "TAS", "7117"],
  ["Richmond",           "TAS", "7025"],
  ["Sorell",             "TAS", "7172"],
  ["Dunalley",           "TAS", "7177"],
  ["Eaglehawk Neck",     "TAS", "7179"],
  ["Port Arthur",        "TAS", "7182"],
  ["New Norfolk",        "TAS", "7140"],
  ["Bothwell",           "TAS", "7030"],
  // TAS — East Coast
  ["Bicheno",            "TAS", "7215"],
  ["Coles Bay",          "TAS", "7215"],
  ["St Helens",          "TAS", "7216"],
  ["Scamander",          "TAS", "7215"],
  ["Swansea",            "TAS", "7190"],
  ["Triabunna",          "TAS", "7190"],
  ["Orford",             "TAS", "7190"],
  // TAS — North & North-West
  ["Smithton",           "TAS", "7330"],
  ["Stanley",            "TAS", "7331"],
  ["Wynyard",            "TAS", "7325"],
  ["Penguin",            "TAS", "7316"],
  ["Latrobe",            "TAS", "7307"],
  ["Sheffield",          "TAS", "7306"],
  ["Deloraine",          "TAS", "7304"],
  ["Westbury",           "TAS", "7303"],
  ["Longford",           "TAS", "7301"],
  ["Evandale",           "TAS", "7212"],
  ["Scottsdale",         "TAS", "7260"],
  ["George Town",        "TAS", "7253"],
  ["Beaconsfield",       "TAS", "7270"],
  // TAS — West Coast
  ["Strahan",            "TAS", "7468"],
  ["Queenstown",         "TAS", "7467"],
  ["Zeehan",             "TAS", "7469"],
  ["Rosebery",           "TAS", "7470"],

  // ACT
  ["Canberra",           "ACT", "2601"],
  ["Braddon",            "ACT", "2612"],
  ["Reid",               "ACT", "2612"],
  ["Turner",             "ACT", "2612"],
  ["Ainslie",            "ACT", "2602"],
  ["Dickson",            "ACT", "2602"],
  ["Lyneham",            "ACT", "2602"],
  ["Watson",             "ACT", "2602"],
  ["Belconnen",          "ACT", "2617"],
  ["Woden",              "ACT", "2606"],
  ["Gungahlin",          "ACT", "2912"],
  ["Tuggeranong",        "ACT", "2900"],
  ["Forrest",            "ACT", "2603"],
  ["Deakin",             "ACT", "2600"],
  ["Griffith",           "ACT", "2603"],
  ["Kingston",           "ACT", "2604"],
  ["Barton",             "ACT", "2600"],
  // ACT — Inner North & South extras
  ["O'Connor",           "ACT", "2602"],
  ["Hackett",            "ACT", "2602"],
  ["Downer",             "ACT", "2602"],
  ["Yarralumla",         "ACT", "2600"],
  ["Manuka",             "ACT", "2603"],
  ["Red Hill",           "ACT", "2603"],
  ["Narrabundah",        "ACT", "2604"],
  ["Fyshwick",           "ACT", "2609"],
  // ACT — Belconnen district
  ["Aranda",             "ACT", "2614"],
  ["Cook",               "ACT", "2614"],
  ["Macquarie",          "ACT", "2614"],
  ["Weetangera",         "ACT", "2614"],
  ["Hawker",             "ACT", "2614"],
  ["Page",               "ACT", "2614"],
  ["Scullin",            "ACT", "2614"],
  ["Kaleen",             "ACT", "2617"],
  ["Giralang",           "ACT", "2617"],
  ["Evatt",              "ACT", "2617"],
  ["Florey",             "ACT", "2615"],
  ["Latham",             "ACT", "2615"],
  ["Macgregor",          "ACT", "2615"],
  ["Charnwood",          "ACT", "2615"],
  ["Dunlop",             "ACT", "2615"],
  ["Fraser",             "ACT", "2615"],
  ["Spence",             "ACT", "2615"],
  ["Melba",              "ACT", "2615"],
  // ACT — Woden Valley
  ["Curtin",             "ACT", "2605"],
  ["Garran",             "ACT", "2605"],
  ["Hughes",             "ACT", "2605"],
  ["Lyons",              "ACT", "2606"],
  ["Phillip",            "ACT", "2606"],
  ["Mawson",             "ACT", "2607"],
  ["Pearce",             "ACT", "2607"],
  ["Torrens",            "ACT", "2607"],
  ["Chifley",            "ACT", "2606"],
  ["Farrer",             "ACT", "2607"],
  ["Isaacs",             "ACT", "2607"],
  // ACT — Tuggeranong district
  ["Calwell",            "ACT", "2905"],
  ["Chisholm",           "ACT", "2905"],
  ["Banks",              "ACT", "2906"],
  ["Conder",             "ACT", "2906"],
  ["Gowrie",             "ACT", "2904"],
  ["Isabella Plains",    "ACT", "2905"],
  ["Macarthur",          "ACT", "2904"],
  ["Monash",             "ACT", "2904"],
  ["Oxley",              "ACT", "2903"],
  ["Theodore",           "ACT", "2905"],
  ["Wanniassa",          "ACT", "2903"],
  ["Bonython",           "ACT", "2905"],
  ["Greenway",           "ACT", "2900"],
  ["Fadden",             "ACT", "2904"],
  ["Gilmore",            "ACT", "2905"],
  ["Kambah",             "ACT", "2902"],
  ["Richardson",         "ACT", "2905"],
  ["Erindale",           "ACT", "2903"],
  // ACT — Gungahlin district
  ["Amaroo",             "ACT", "2914"],
  ["Bonner",             "ACT", "2914"],
  ["Crace",              "ACT", "2911"],
  ["Forde",              "ACT", "2914"],
  ["Franklin",           "ACT", "2913"],
  ["Harrison",           "ACT", "2914"],
  ["Mitchell",           "ACT", "2911"],
  ["Moncrieff",          "ACT", "2914"],
  ["Ngunnawal",          "ACT", "2913"],
  ["Nicholls",           "ACT", "2913"],
  ["Palmerston",         "ACT", "2913"],
  ["Throsby",            "ACT", "2914"],
  // ACT — Weston Creek & Molonglo
  ["Chapman",            "ACT", "2611"],
  ["Duffy",              "ACT", "2611"],
  ["Holder",             "ACT", "2611"],
  ["Stirling",           "ACT", "2611"],
  ["Waramanga",          "ACT", "2611"],
  ["Weston",             "ACT", "2611"],
  ["Rivett",             "ACT", "2611"],
  ["Wright",             "ACT", "2611"],
  ["Coombs",             "ACT", "2611"],
  ["Denman Prospect",    "ACT", "2611"],

  // NT
  ["Darwin",             "NT",  "0800"],
  ["Palmerston",         "NT",  "0830"],
  ["Casuarina",          "NT",  "0810"],
  ["Nightcliff",         "NT",  "0810"],
  ["Alice Springs",      "NT",  "0870"],
  // NT — Regional
  ["Katherine",          "NT",  "0850"],
  ["Tennant Creek",      "NT",  "0860"],
  ["Nhulunbuy",          "NT",  "0880"],
  ["Yulara",             "NT",  "0872"],
  ["Jabiru",             "NT",  "0886"],
  ["Howard Springs",     "NT",  "0835"],
  ["Humpty Doo",         "NT",  "0836"],
  ["Berry Springs",      "NT",  "0838"],
];

// Keyed by "Suburb, STATE" — e.g. "Richmond, VIC"
export const SUBURB_LOOKUP: Record<string, SuburbEntry> = Object.fromEntries(
  SUBURBS_RAW.map(([suburb, state, postcode]) => [
    `${suburb}, ${state}`,
    { suburb, state, postcode },
  ])
);

export function getSuburbInfo(key: string): SuburbEntry | undefined {
  return SUBURB_LOOKUP[key];
}

export function getAllSuburbKeys(): string[] {
  return Object.keys(SUBURB_LOOKUP).sort();
}
