export interface SuburbEntry {
  suburb: string;
  state: string;
  postcode: string;
}

// [suburb, state, postcode]
const SUBURBS_RAW: [string, string, string][] = [
  // VIC — Melbourne CBD & surrounds
  ["Melbourne",          "VIC", "3000"],
  ["Southbank",          "VIC", "3006"],
  ["Docklands",          "VIC", "3008"],
  ["West Melbourne",     "VIC", "3003"],
  ["North Melbourne",    "VIC", "3051"],
  ["Parkville",          "VIC", "3052"],
  // VIC — Inner North
  ["Carlton",            "VIC", "3053"],
  ["Carlton North",      "VIC", "3054"],
  ["Fitzroy",            "VIC", "3065"],
  ["Fitzroy North",      "VIC", "3068"],
  ["Collingwood",        "VIC", "3066"],
  ["Abbotsford",         "VIC", "3067"],
  ["Richmond",           "VIC", "3121"],
  ["Brunswick",          "VIC", "3056"],
  ["Brunswick East",     "VIC", "3057"],
  ["Brunswick West",     "VIC", "3055"],
  ["Coburg",             "VIC", "3058"],
  ["Coburg North",       "VIC", "3058"],
  ["Pascoe Vale",        "VIC", "3044"],
  ["Pascoe Vale South",  "VIC", "3044"],
  ["Oak Park",           "VIC", "3046"],
  ["Glenroy",            "VIC", "3046"],
  ["Broadmeadows",       "VIC", "3047"],
  ["Dallas",             "VIC", "3047"],
  ["Tullamarine",        "VIC", "3043"],
  ["Preston",            "VIC", "3072"],
  ["Reservoir",          "VIC", "3073"],
  ["Thomastown",         "VIC", "3074"],
  ["Lalor",              "VIC", "3075"],
  ["Epping",             "VIC", "3076"],
  ["Bundoora",           "VIC", "3083"],
  ["Mill Park",          "VIC", "3082"],
  ["South Morang",       "VIC", "3752"],
  ["Greensborough",      "VIC", "3088"],
  ["Diamond Creek",      "VIC", "3089"],
  ["Eltham",             "VIC", "3095"],
  ["Montmorency",        "VIC", "3094"],
  // VIC — Inner West
  ["Footscray",          "VIC", "3011"],
  ["Yarraville",         "VIC", "3013"],
  ["Seddon",             "VIC", "3011"],
  ["Maribyrnong",        "VIC", "3032"],
  ["Ascot Vale",         "VIC", "3032"],
  ["Flemington",         "VIC", "3031"],
  ["Kensington",         "VIC", "3031"],
  ["Essendon",           "VIC", "3040"],
  ["Moonee Ponds",       "VIC", "3039"],
  ["Newport",            "VIC", "3015"],
  ["Williamstown",       "VIC", "3016"],
  ["Spotswood",          "VIC", "3015"],
  ["Altona",             "VIC", "3018"],
  ["Altona North",       "VIC", "3025"],
  ["Altona Meadows",     "VIC", "3028"],
  ["Laverton",           "VIC", "3028"],
  ["Sunshine",           "VIC", "3020"],
  ["Sunshine North",     "VIC", "3020"],
  ["St Albans",          "VIC", "3021"],
  ["Deer Park",          "VIC", "3023"],
  ["Werribee",           "VIC", "3030"],
  ["Hoppers Crossing",   "VIC", "3029"],
  ["Tarneit",            "VIC", "3029"],
  ["Point Cook",         "VIC", "3030"],
  ["Wyndham Vale",       "VIC", "3024"],
  // VIC — Inner South
  ["South Yarra",        "VIC", "3141"],
  ["Toorak",             "VIC", "3142"],
  ["Prahran",            "VIC", "3181"],
  ["Windsor",            "VIC", "3181"],
  ["Armadale",           "VIC", "3143"],
  ["Glen Iris",          "VIC", "3146"],
  ["Malvern",            "VIC", "3144"],
  ["Malvern East",       "VIC", "3145"],
  ["Caulfield",          "VIC", "3162"],
  ["Caulfield North",    "VIC", "3161"],
  ["Caulfield South",    "VIC", "3162"],
  ["Elsternwick",        "VIC", "3185"],
  ["Ormond",             "VIC", "3204"],
  ["McKinnon",           "VIC", "3204"],
  ["Bentleigh",          "VIC", "3204"],
  ["Bentleigh East",     "VIC", "3165"],
  ["Carnegie",           "VIC", "3163"],
  ["Murrumbeena",        "VIC", "3163"],
  ["Oakleigh",           "VIC", "3166"],
  ["Oakleigh East",      "VIC", "3166"],
  ["Oakleigh South",     "VIC", "3167"],
  ["Huntingdale",        "VIC", "3166"],
  ["Moorabbin",          "VIC", "3189"],
  ["Highett",            "VIC", "3190"],
  ["Cheltenham",         "VIC", "3192"],
  ["Beaumaris",          "VIC", "3193"],
  ["Mentone",            "VIC", "3194"],
  ["Mordialloc",         "VIC", "3195"],
  ["Parkdale",           "VIC", "3195"],
  ["Sandringham",        "VIC", "3191"],
  ["Hampton",            "VIC", "3188"],
  ["Brighton",           "VIC", "3186"],
  ["Brighton East",      "VIC", "3187"],
  // VIC — Port Phillip & St Kilda
  ["St Kilda",           "VIC", "3182"],
  ["Elwood",             "VIC", "3184"],
  ["Port Melbourne",     "VIC", "3207"],
  ["Albert Park",        "VIC", "3206"],
  ["South Melbourne",    "VIC", "3205"],
  // VIC — Inner East
  ["Hawthorn",           "VIC", "3122"],
  ["Hawthorn East",      "VIC", "3123"],
  ["Camberwell",         "VIC", "3124"],
  ["Canterbury",         "VIC", "3126"],
  ["Balwyn",             "VIC", "3103"],
  ["Balwyn North",       "VIC", "3104"],
  ["Kew",                "VIC", "3101"],
  ["Kew East",           "VIC", "3102"],
  ["Box Hill",           "VIC", "3128"],
  ["Box Hill North",     "VIC", "3129"],
  ["Box Hill South",     "VIC", "3128"],
  ["Blackburn",          "VIC", "3130"],
  ["Doncaster",          "VIC", "3108"],
  ["Doncaster East",     "VIC", "3109"],
  ["Templestowe",        "VIC", "3106"],
  ["Templestowe Lower",  "VIC", "3107"],
  ["Burwood",            "VIC", "3125"],
  ["Burwood East",       "VIC", "3151"],
  ["Ashwood",            "VIC", "3147"],
  ["Chadstone",          "VIC", "3148"],
  ["Glen Waverley",      "VIC", "3150"],
  ["Mount Waverley",     "VIC", "3149"],
  ["Wheelers Hill",      "VIC", "3150"],
  ["Mulgrave",           "VIC", "3170"],
  // VIC — South East
  ["Clayton",            "VIC", "3168"],
  ["Clayton South",      "VIC", "3169"],
  ["Springvale",         "VIC", "3171"],
  ["Springvale South",   "VIC", "3172"],
  ["Noble Park",         "VIC", "3174"],
  ["Dandenong",          "VIC", "3175"],
  ["Dandenong North",    "VIC", "3175"],
  ["Rowville",           "VIC", "3178"],
  ["Ferntree Gully",     "VIC", "3156"],
  ["Bayswater",          "VIC", "3153"],
  ["Boronia",            "VIC", "3155"],
  ["Wantirna",           "VIC", "3152"],
  ["Frankston",          "VIC", "3199"],
  ["Frankston North",    "VIC", "3200"],
  ["Langwarrin",         "VIC", "3910"],
  ["Mount Eliza",        "VIC", "3930"],
  ["Mornington",         "VIC", "3931"],
  ["Mount Martha",       "VIC", "3934"],
  ["Rosebud",            "VIC", "3939"],
  ["Rye",                "VIC", "3941"],
  ["Sorrento",           "VIC", "3943"],
  // VIC — Regional
  ["Geelong",            "VIC", "3220"],
  ["Geelong West",       "VIC", "3218"],
  ["Newtown",            "VIC", "3220"],
  ["Highton",            "VIC", "3216"],
  ["Belmont",            "VIC", "3216"],
  ["Grovedale",          "VIC", "3216"],
  ["South Geelong",      "VIC", "3220"],
  ["Ballarat",           "VIC", "3350"],
  ["Ballarat East",      "VIC", "3350"],
  ["Bendigo",            "VIC", "3550"],
  ["Kangaroo Flat",      "VIC", "3555"],
  ["Strathfieldsaye",    "VIC", "3551"],
  ["Shepparton",         "VIC", "3630"],
  ["Mooroopna",          "VIC", "3629"],
  ["Mildura",            "VIC", "3500"],
  ["Irymple",            "VIC", "3498"],
  ["Warrnambool",        "VIC", "3280"],
  ["Traralgon",          "VIC", "3844"],
  ["Morwell",            "VIC", "3840"],
  ["Moe",                "VIC", "3825"],
  ["Echuca",             "VIC", "3564"],
  ["Wodonga",            "VIC", "3690"],
  ["Swan Hill",          "VIC", "3585"],
  ["Horsham",            "VIC", "3400"],
  ["Wangaratta",         "VIC", "3677"],
  ["Sale",               "VIC", "3850"],

  // NSW — Sydney CBD & surrounds
  ["Sydney",             "NSW", "2000"],
  ["Haymarket",          "NSW", "2000"],
  ["Pyrmont",            "NSW", "2009"],
  ["Ultimo",             "NSW", "2007"],
  ["Glebe",              "NSW", "2037"],
  ["Forest Lodge",       "NSW", "2037"],
  ["Annandale",          "NSW", "2038"],
  ["Balmain",            "NSW", "2041"],
  ["Rozelle",            "NSW", "2039"],
  ["Leichhardt",         "NSW", "2040"],
  // NSW — Inner East
  ["Surry Hills",        "NSW", "2010"],
  ["Darlinghurst",       "NSW", "2010"],
  ["Potts Point",        "NSW", "2011"],
  ["Elizabeth Bay",      "NSW", "2011"],
  ["Woolloomooloo",      "NSW", "2011"],
  ["Paddington",         "NSW", "2021"],
  ["Woollahra",          "NSW", "2025"],
  ["Edgecliff",          "NSW", "2027"],
  ["Double Bay",         "NSW", "2028"],
  ["Rose Bay",           "NSW", "2029"],
  ["Bellevue Hill",      "NSW", "2023"],
  ["Vaucluse",           "NSW", "2030"],
  ["Watsons Bay",        "NSW", "2030"],
  ["Bondi",              "NSW", "2026"],
  ["Bondi Beach",        "NSW", "2026"],
  ["Bondi Junction",     "NSW", "2022"],
  ["Bronte",             "NSW", "2024"],
  ["Coogee",             "NSW", "2034"],
  ["Randwick",           "NSW", "2031"],
  ["Kensington",         "NSW", "2033"],
  ["Kingsford",          "NSW", "2032"],
  // NSW — Inner West
  ["Newtown",            "NSW", "2042"],
  ["Erskineville",       "NSW", "2043"],
  ["Redfern",            "NSW", "2016"],
  ["Waterloo",           "NSW", "2017"],
  ["Alexandria",         "NSW", "2015"],
  ["Zetland",            "NSW", "2017"],
  ["Marrickville",       "NSW", "2204"],
  ["Dulwich Hill",       "NSW", "2203"],
  ["Stanmore",           "NSW", "2048"],
  ["Petersham",          "NSW", "2049"],
  ["Enmore",             "NSW", "2042"],
  // NSW — North Shore
  ["North Sydney",       "NSW", "2060"],
  ["Milsons Point",      "NSW", "2061"],
  ["Kirribilli",         "NSW", "2061"],
  ["Neutral Bay",        "NSW", "2089"],
  ["Cremorne",           "NSW", "2090"],
  ["Mosman",             "NSW", "2088"],
  ["Crows Nest",         "NSW", "2065"],
  ["St Leonards",        "NSW", "2065"],
  ["Artarmon",           "NSW", "2064"],
  ["Willoughby",         "NSW", "2068"],
  ["Chatswood",          "NSW", "2067"],
  ["Lane Cove",          "NSW", "2066"],
  ["Longueville",        "NSW", "2066"],
  ["Manly",              "NSW", "2095"],
  ["Manly Vale",         "NSW", "2093"],
  ["Freshwater",         "NSW", "2096"],
  ["Dee Why",            "NSW", "2099"],
  ["Collaroy",           "NSW", "2097"],
  ["Narrabeen",          "NSW", "2101"],
  ["Mona Vale",          "NSW", "2103"],
  ["Avalon Beach",       "NSW", "2107"],
  ["Palm Beach",         "NSW", "2108"],
  // NSW — Upper North Shore
  ["Gordon",             "NSW", "2072"],
  ["Killara",            "NSW", "2071"],
  ["Lindfield",          "NSW", "2070"],
  ["Roseville",          "NSW", "2069"],
  ["St Ives",            "NSW", "2075"],
  ["Turramurra",         "NSW", "2074"],
  ["Wahroonga",          "NSW", "2076"],
  ["Hornsby",            "NSW", "2077"],
  ["Pymble",             "NSW", "2073"],
  // NSW — Western Sydney
  ["Parramatta",         "NSW", "2150"],
  ["Granville",          "NSW", "2142"],
  ["Westmead",           "NSW", "2145"],
  ["Merrylands",         "NSW", "2160"],
  ["Guildford",          "NSW", "2161"],
  ["Auburn",             "NSW", "2144"],
  ["Lidcombe",           "NSW", "2141"],
  ["Homebush",           "NSW", "2140"],
  ["Strathfield",        "NSW", "2135"],
  ["Burwood",            "NSW", "2134"],
  ["Croydon",            "NSW", "2132"],
  ["Ashfield",           "NSW", "2131"],
  ["Liverpool",          "NSW", "2170"],
  ["Campbelltown",       "NSW", "2560"],
  ["Penrith",            "NSW", "2750"],
  ["Blacktown",          "NSW", "2148"],
  ["Seven Hills",        "NSW", "2147"],
  ["Baulkham Hills",     "NSW", "2153"],
  ["Castle Hill",        "NSW", "2154"],
  ["Kellyville",         "NSW", "2155"],
  ["Rouse Hill",         "NSW", "2155"],
  ["Richmond",           "NSW", "2753"],
  // NSW — Regional
  ["Newcastle",          "NSW", "2300"],
  ["Hamilton",           "NSW", "2303"],
  ["Maitland",           "NSW", "2320"],
  ["Cessnock",           "NSW", "2325"],
  ["Charlestown",        "NSW", "2290"],
  ["Warners Bay",        "NSW", "2282"],
  ["Wollongong",         "NSW", "2500"],
  ["Figtree",            "NSW", "2525"],
  ["Shellharbour",       "NSW", "2529"],
  ["Kiama",              "NSW", "2533"],
  ["Nowra",              "NSW", "2541"],
  ["Batemans Bay",       "NSW", "2536"],
  ["Coffs Harbour",      "NSW", "2450"],
  ["Port Macquarie",     "NSW", "2444"],
  ["Tamworth",           "NSW", "2340"],
  ["Armidale",           "NSW", "2350"],
  ["Dubbo",              "NSW", "2830"],
  ["Orange",             "NSW", "2800"],
  ["Bathurst",           "NSW", "2795"],
  ["Wagga Wagga",        "NSW", "2650"],
  ["Albury",             "NSW", "2640"],
  ["Queanbeyan",         "NSW", "2620"],

  // QLD — Brisbane CBD & inner
  ["Brisbane City",      "QLD", "4000"],
  ["South Brisbane",     "QLD", "4101"],
  ["West End",           "QLD", "4101"],
  ["Woolloongabba",      "QLD", "4102"],
  ["Spring Hill",        "QLD", "4004"],
  ["Fortitude Valley",   "QLD", "4006"],
  ["New Farm",           "QLD", "4005"],
  ["Newstead",           "QLD", "4006"],
  ["Teneriffe",          "QLD", "4005"],
  ["Paddington",         "QLD", "4064"],
  ["Red Hill",           "QLD", "4059"],
  ["Bardon",             "QLD", "4065"],
  ["Ashgrove",           "QLD", "4060"],
  ["Kelvin Grove",       "QLD", "4059"],
  ["Herston",            "QLD", "4006"],
  ["Lutwyche",           "QLD", "4030"],
  ["Windsor",            "QLD", "4030"],
  ["Clayfield",          "QLD", "4011"],
  ["Ascot",              "QLD", "4007"],
  ["Hamilton",           "QLD", "4007"],
  ["Albion",             "QLD", "4010"],
  ["Bowen Hills",        "QLD", "4006"],
  // QLD — South Brisbane
  ["Annerley",           "QLD", "4103"],
  ["Moorooka",           "QLD", "4105"],
  ["Salisbury",          "QLD", "4107"],
  ["Sunnybank",          "QLD", "4109"],
  ["Sunnybank Hills",    "QLD", "4109"],
  ["Carindale",          "QLD", "4152"],
  ["Carina",             "QLD", "4152"],
  ["Camp Hill",          "QLD", "4152"],
  ["Holland Park",       "QLD", "4121"],
  ["Greenslopes",        "QLD", "4120"],
  ["Coorparoo",          "QLD", "4151"],
  ["East Brisbane",      "QLD", "4169"],
  ["Norman Park",        "QLD", "4170"],
  // QLD — North Brisbane
  ["Chermside",          "QLD", "4032"],
  ["Aspley",             "QLD", "4034"],
  ["Stafford",           "QLD", "4053"],
  ["Wavell Heights",     "QLD", "4012"],
  ["Nundah",             "QLD", "4012"],
  ["Northgate",          "QLD", "4013"],
  ["Sandgate",           "QLD", "4017"],
  ["Bracken Ridge",      "QLD", "4017"],
  // QLD — West Brisbane
  ["Kenmore",            "QLD", "4069"],
  ["Chapel Hill",        "QLD", "4069"],
  ["Indooroopilly",      "QLD", "4068"],
  ["Toowong",            "QLD", "4066"],
  ["Auchenflower",       "QLD", "4066"],
  ["Milton",             "QLD", "4064"],
  // QLD — Ipswich
  ["Ipswich",            "QLD", "4305"],
  // QLD — Gold Coast
  ["Surfers Paradise",   "QLD", "4217"],
  ["Broadbeach",         "QLD", "4218"],
  ["Mermaid Beach",      "QLD", "4218"],
  ["Burleigh Heads",     "QLD", "4220"],
  ["Robina",             "QLD", "4226"],
  ["Varsity Lakes",      "QLD", "4227"],
  ["Mudgeeraba",         "QLD", "4213"],
  ["Nerang",             "QLD", "4211"],
  ["Southport",          "QLD", "4215"],
  ["Main Beach",         "QLD", "4217"],
  ["Labrador",           "QLD", "4215"],
  ["Parkwood",           "QLD", "4214"],
  ["Helensvale",         "QLD", "4212"],
  ["Hope Island",        "QLD", "4212"],
  ["Coomera",            "QLD", "4209"],
  ["Pimpama",            "QLD", "4209"],
  // QLD — Sunshine Coast
  ["Noosa Heads",        "QLD", "4567"],
  ["Noosaville",         "QLD", "4566"],
  ["Tewantin",           "QLD", "4565"],
  ["Buderim",            "QLD", "4556"],
  ["Mooloolaba",         "QLD", "4557"],
  ["Maroochydore",       "QLD", "4558"],
  ["Nambour",            "QLD", "4560"],
  ["Caloundra",          "QLD", "4551"],
  ["Kawana Waters",      "QLD", "4575"],
  ["Sippy Downs",        "QLD", "4556"],
  // QLD — Regional
  ["Toowoomba",          "QLD", "4350"],
  ["Cairns",             "QLD", "4870"],
  ["Townsville",         "QLD", "4810"],
  ["Rockhampton",        "QLD", "4700"],
  ["Mackay",             "QLD", "4740"],
  ["Bundaberg",          "QLD", "4670"],
  ["Hervey Bay",         "QLD", "4655"],
  ["Gladstone",          "QLD", "4680"],

  // SA — Adelaide
  ["Adelaide",           "SA",  "5000"],
  ["North Adelaide",     "SA",  "5006"],
  ["Norwood",            "SA",  "5067"],
  ["Rose Park",          "SA",  "5067"],
  ["Parkside",           "SA",  "5063"],
  ["Unley",              "SA",  "5061"],
  ["Malvern",            "SA",  "5061"],
  ["Burnside",           "SA",  "5066"],
  ["Glenside",           "SA",  "5065"],
  ["Mitcham",            "SA",  "5062"],
  ["Black Forest",       "SA",  "5035"],
  ["Prospect",           "SA",  "5082"],
  ["Nailsworth",         "SA",  "5083"],
  ["Blair Athol",        "SA",  "5084"],
  ["Enfield",            "SA",  "5085"],
  ["Gepps Cross",        "SA",  "5094"],
  ["Mawson Lakes",       "SA",  "5095"],
  ["Salisbury",          "SA",  "5108"],
  ["Elizabeth",          "SA",  "5112"],
  ["Marion",             "SA",  "5043"],
  ["Oaklands Park",      "SA",  "5046"],
  ["Plympton",           "SA",  "5038"],
  ["Mile End",           "SA",  "5031"],
  ["Thebarton",          "SA",  "5031"],
  ["Henley Beach",       "SA",  "5022"],
  ["Glenelg",            "SA",  "5045"],
  ["Brighton",           "SA",  "5048"],
  ["Hallett Cove",       "SA",  "5158"],
  ["Christies Beach",    "SA",  "5165"],
  ["Noarlunga",          "SA",  "5168"],
  ["McLaren Vale",       "SA",  "5171"],
  ["Glen Osmond",        "SA",  "5064"],
  ["Dulwich",            "SA",  "5065"],
  ["Aldgate",            "SA",  "5154"],
  ["Stirling",           "SA",  "5152"],
  ["Crafers",            "SA",  "5152"],
  ["Hahndorf",           "SA",  "5245"],
  ["Mount Gambier",      "SA",  "5290"],
  ["Whyalla",            "SA",  "5600"],
  ["Port Augusta",       "SA",  "5700"],
  ["Port Pirie",         "SA",  "5540"],
  ["Victor Harbor",      "SA",  "5211"],
  ["Murray Bridge",      "SA",  "5253"],

  // WA — Perth
  ["Perth",              "WA",  "6000"],
  ["Northbridge",        "WA",  "6003"],
  ["East Perth",         "WA",  "6004"],
  ["West Perth",         "WA",  "6005"],
  ["Subiaco",            "WA",  "6008"],
  ["Cottesloe",          "WA",  "6011"],
  ["Claremont",          "WA",  "6010"],
  ["Nedlands",           "WA",  "6009"],
  ["Dalkeith",           "WA",  "6009"],
  ["Applecross",         "WA",  "6153"],
  ["South Perth",        "WA",  "6151"],
  ["Como",               "WA",  "6152"],
  ["Victoria Park",      "WA",  "6100"],
  ["Burswood",           "WA",  "6100"],
  ["Rivervale",          "WA",  "6103"],
  ["Belmont",            "WA",  "6104"],
  ["Joondalup",          "WA",  "6027"],
  ["Wanneroo",           "WA",  "6065"],
  ["Ellenbrook",         "WA",  "6069"],
  ["Midland",            "WA",  "6056"],
  ["Kalamunda",          "WA",  "6076"],
  ["Mundaring",          "WA",  "6073"],
  ["Fremantle",          "WA",  "6160"],
  ["North Fremantle",    "WA",  "6159"],
  ["Bibra Lake",         "WA",  "6163"],
  ["Hamilton Hill",      "WA",  "6163"],
  ["Coogee",             "WA",  "6166"],
  ["Rockingham",         "WA",  "6168"],
  ["Mandurah",           "WA",  "6210"],
  ["Baldivis",           "WA",  "6171"],
  ["Scarborough",        "WA",  "6019"],
  ["Wembley",            "WA",  "6014"],
  ["Floreat",            "WA",  "6014"],
  ["Churchlands",        "WA",  "6018"],
  ["Karrinyup",          "WA",  "6018"],
  ["Stirling",           "WA",  "6021"],
  ["Bunbury",            "WA",  "6230"],
  ["Geraldton",          "WA",  "6530"],
  ["Kalgoorlie",         "WA",  "6430"],
  ["Albany",             "WA",  "6330"],
  ["Broome",             "WA",  "6725"],
  ["Port Hedland",       "WA",  "6721"],

  // TAS
  ["Hobart",             "TAS", "7000"],
  ["Sandy Bay",          "TAS", "7005"],
  ["Battery Point",      "TAS", "7004"],
  ["New Town",           "TAS", "7008"],
  ["Glenorchy",          "TAS", "7010"],
  ["Moonah",             "TAS", "7009"],
  ["Lindisfarne",        "TAS", "7015"],
  ["Clarence",           "TAS", "7011"],
  ["Rokeby",             "TAS", "7019"],
  ["Launceston",         "TAS", "7250"],
  ["Newnham",            "TAS", "7248"],
  ["Kings Meadows",      "TAS", "7249"],
  ["Devonport",          "TAS", "7310"],
  ["Burnie",             "TAS", "7320"],
  ["Ulverstone",         "TAS", "7315"],

  // ACT
  ["Canberra",           "ACT", "2601"],
  ["Braddon",            "ACT", "2612"],
  ["Reid",               "ACT", "2612"],
  ["Turner",             "ACT", "2612"],
  ["Ainslie",            "ACT", "2602"],
  ["Dickson",            "ACT", "2602"],
  ["Lyneham",            "ACT", "2602"],
  ["Watson",             "ACT", "2602"],
  ["Belconnen",          "ACT", "2617"],
  ["Woden",              "ACT", "2606"],
  ["Gungahlin",          "ACT", "2912"],
  ["Tuggeranong",        "ACT", "2900"],
  ["Forrest",            "ACT", "2603"],
  ["Deakin",             "ACT", "2600"],
  ["Griffith",           "ACT", "2603"],
  ["Kingston",           "ACT", "2604"],
  ["Barton",             "ACT", "2600"],

  // NT
  ["Darwin",             "NT",  "0800"],
  ["Palmerston",         "NT",  "0830"],
  ["Casuarina",          "NT",  "0810"],
  ["Nightcliff",         "NT",  "0810"],
  ["Alice Springs",      "NT",  "0870"],
];

// Keyed by "Suburb, STATE" — e.g. "Richmond, VIC"
export const SUBURB_LOOKUP: Record<string, SuburbEntry> = Object.fromEntries(
  SUBURBS_RAW.map(([suburb, state, postcode]) => [
    `${suburb}, ${state}`,
    { suburb, state, postcode },
  ])
);

export function getSuburbInfo(key: string): SuburbEntry | undefined {
  return SUBURB_LOOKUP[key];
}

export function getAllSuburbKeys(): string[] {
  return Object.keys(SUBURB_LOOKUP).sort();
}
